name: Sync Hugging Face Model to GitHub

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 自动同步
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main  # 仅在 main 分支有变动时触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Download Model from Hugging Face
        run: |
          from huggingface_hub import snapshot_download
          snapshot_download(repo_id="zeng981/nlpgemma29B", local_dir="hf_model")
        shell: python

      - name: Commit and Push to GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add hf_model
          git commit -m "Sync nlpgemma29B model from Hugging Face" || echo "No changes to commit"
          git push
