name: Sync Hugging Face Models to GitHub

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 自动同步
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main  # 仅在 main 分支有变动时触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Download nlpgemma29B Model
        run: |
          from huggingface_hub import snapshot_download
          snapshot_download(repo_id="zeng981/nlpgemma29B", local_dir="hf_models/nlpgemma29B")
        shell: python

      - name: Download NLPGLM-4-9B Model
        run: |
          from huggingface_hub import snapshot_download
          snapshot_download(repo_id="zeng981/NLPGLM-4-9B", local_dir="hf_models/NLPGLM-4-9B")
        shell: python

      - name: Download NLPqwen-1.8b Model
        run: |
          from huggingface_hub import snapshot_download
          snapshot_download(repo_id="zeng981/NLPqwen-1.8b", local_dir="hf_models/NLPqwen-1.8b")
        shell: python

      - name: Download NLPLlama3.2-3b Model
        run: |
          from huggingface_hub import snapshot_download
          snapshot_download(repo_id="zeng981/NLPLlama3.2-3b", local_dir="hf_models/NLPLlama3.2-3b")
        shell: python

      - name: Download NLPQwen2-7b Model
        run: |
          from huggingface_hub import snapshot_download
          snapshot_download(repo_id="zeng981/NLPQwen2-7b", local_dir="hf_models/NLPQwen2-7b")
        shell: python

      - name: Commit and Push to GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add hf_models
          git commit -m "Sync 5 Hugging Face models from Hugging Face" || echo "No changes to commit"
          git push
