name: Sync Hugging Face Models to GitHub Releases

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 自动同步
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main  # 仅在 main 分支有变动时触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Download Hugging Face Models
        run: |
          from huggingface_hub import snapshot_download
          import os
          models = [
              "zeng981/nlpgemma29B",
              "zeng981/NLPGLM-4-9B",
              "zeng981/NLPqwen-1.8b",
              "zeng981/NLPLlama3.2-3b",
              "zeng981/NLPQwen2-7b"
          ]
          os.makedirs("hf_models", exist_ok=True)
          for model in models:
              snapshot_download(repo_id=model, local_dir=f"hf_models/{model.split('/')[-1]}")
        shell: python

      - name: Create ZIP Archive
        run: |
          zip -r hf_models.zip hf_models/

      - name: Upload Model ZIP to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: hf_models.zip
          tag_name: "latest"
          name: "Latest Hugging Face Models"
          body: "This release contains the latest backup of Hugging Face models."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
